name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 19 * * *'  # UTC 时间 19:00 (北京时间 +8)
  
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      # 检出当前仓库代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: refs/heads/main  # 明确指定完整的分支引用
      
      # 配置 Git
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      # 添加上游仓库
      - name: Add Remote Upstream
        run: |
          git remote add upstream https://github.com/chxm1023/Rewrite.git
          git remote -v
      
      # 同步上游仓库的变更
      - name: Sync with Upstream
        run: |
          # 删除可能存在的陈旧引用
          git remote prune origin
          git remote prune upstream
          
          # 获取最新的分支信息
          git fetch upstream
          git fetch origin
          
          # 确保我们在本地 main 分支上
          git switch -c temp-main || git switch temp-main
          
          # 重置到 origin/main
          git reset --hard origin/main
          
          # 合并上游的更改
          git merge upstream/main --allow-unrelated-histories -X theirs --no-edit
          
          # 推送更改到 fork 仓库
          git push origin HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
